patch-playstore: remove pointless dependency on standalone aapt

diff --git a/patch-playstore b/patch-playstore
--- a/patch-playstore
+++ b/patch-playstore
@@ -7,38 +7,39 @@ strings_insert="    <string name=\"fake_signature\">308204433082032ba00302010202
 
 error () {
 	echo -e "\nERROR: ${@}\n"
-	[ "$DEBUG" ] || rm -rf "${gplay_work}" "${gplay_orig}"
+	[ "$DEBUG" ] || rm -rf "${gplay_work}" "${gplay_orig}" play_unpack
 	exit 1
 }
 
 setup () {
 	command -v apktool >/dev/null || error "apktool not found"
-	command -v aapt >/dev/null || error "aapt not found"
+}
 
-	gplay_version=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $4}')
-	gplay_version_p=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $6}' | sed -e 's/\ .*//')
-	gplay_name=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $2}')
+unpack_gplay () {
+	echo "[1] Unpacking APK"
+	rm -rf "${gplay_work}" "${gplay_orig}" play_unpack
+	apktool d --no-src ${APKTOOL_FLAGS} "${gplay}" -o play_unpack || error "apktool failed to unpack ${gplay}"
+
+	gplay_version=$(grep 'versionCode: ' "play_unpack/apktool.yml" | cut -d' ' -f4- | tr -d "'")
+	gplay_version_p=$(grep 'versionName: ' "play_unpack/apktool.yml" | cut -d' ' -f4)
+	gplay_name=$(grep '<manifest' "play_unpack/AndroidManifest.xml" | grep -o 'package=[^ ]*' | cut -d= -f2 | tr -d '"')
 
 	[[ "${gplay_name}" != com.android.vending ]] && error "Given file is not a Play Store apk"
 	[ -z "${gplay_version}" ] && error "Could not determine Play Store version code"
 	[[ ! "${gplay_version_p}" != ^[0-9][0-9].[0-9].[0-9][0-9]$ ]] && error "Version seems not like a Play Store version"
-
-	gplay_orig="play_${gplay_version_p}.orig"
-	gplay_work="play_${gplay_version_p}"
-	gplay_dist="${gplay_work}/dist/$(basename "${gplay}")"
-	gplay_out="Phonesky_${gplay_version_p}_patched.apk"
 
 	echo "Detected Play Store:
 
 	APK:	$(basename "${gplay}")
 	VER:	${gplay_version} [${gplay_version_p}]
 	"
-}
 
-unpack_gplay () {
-	echo "[1] Unpacking APK"
-	rm -rf "${gplay_work}" "${gplay_orig}"
-	apktool d --no-src ${APKTOOL_FLAGS} "${gplay}" -o "${gplay_work}" || error "apktool failed to unpack ${gplay}"
+	gplay_orig="play_${gplay_version_p}.orig"
+	gplay_work="play_${gplay_version_p}"
+	gplay_dist="${gplay_work}/dist/$(basename "${gplay}")"
+	gplay_out="Phonesky_${gplay_version_p}_patched.apk"
+
+	mv play_unpack "${gplay_work}"
 
 	grep -q FAKE_PACKAGE_SIGNATURE "${gplay_work}/AndroidManifest.xml" && error "APK already patched!"
 
